# Generated by Django 4.2.1 on 2023-07-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_visit",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Visit"
            ),
        ),
    ]
