# Generated by Django 4.2.1 on 2023-08-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_last_visit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_visit",
        ),
        migrations.AddField(
            model_name="user",
            name="previous_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Previous Login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="recent_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Most Recent Login"
            ),
        ),
    ]
