# Generated by Django 4.0.4 on 2022-06-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_caregiver_student_house_group_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
    ]
