# Generated by Django 4.0.6 on 2022-07-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='house_group',
            field=models.CharField(blank=True, choices=[('A', 'Anderson'), ('B', 'Begg'), ('R', 'Ross'), ('H', 'Herron'), ('S', 'Somerville')], max_length=20, null=True, verbose_name='House Group'),
        ),
    ]
