# Generated by Django 4.0.6 on 2022-08-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_next_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='next_milestone',
        ),
    ]
