# Generated by Django 4.2 on 2023-05-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_remove_student_next_milestone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="house_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Anderson"),
                    ("B", "Begg"),
                    ("R", "Ross"),
                    ("H", "Herron"),
                    ("S", "Somerville"),
                ],
                default="",
                max_length=20,
                verbose_name="House Group",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="tutor_room",
            field=models.CharField(
                blank=True, default="", max_length=3, verbose_name="Tutor Room"
            ),
        ),
    ]
