# Generated by Django 4.2.1 on 2023-07-05 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0008_remove_student_caregiver_caregiver_students"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caregiver",
            options={"verbose_name": "Caregiver", "verbose_name_plural": "Caregivers"},
        ),
    ]
