version = 1

test_patterns = ["**/tests.py"]

exclude_patterns = ["**/migrations/**", "**/tests.py"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
