# Generated by Django 4.0.4 on 2022-06-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commendation',
            name='reason',
            field=models.TextField(max_length=500, verbose_name='Reason'),
        ),
    ]
