# Generated by Django 4.0.6 on 2022-08-12 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_next_milestone'),
        ('commendations', '0004_alter_commendation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('milestone_type', models.IntegerField(choices=[(25, "Dean's Certificate"), (50, 'Green Jr School spirit badge'), (100, 'Blue Jr School spirit badge'), (150, 'Gold Jr School spirit badge')], verbose_name='Milestone Type')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time given')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
            },
        ),
    ]
