# Generated by Django 4.0.6 on 2022-08-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commendations', '0005_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='milestone_type',
            field=models.IntegerField(choices=[(25, "Dean's Certificate - 25 commendations"), (50, 'Green Jr School spirit badge - 50 commendations'), (100, 'Blue Jr School spirit badge - 100 commendations'), (150, 'Gold Jr School spirit badge - 150 commendations')], verbose_name='Milestone Type'),
        ),
    ]
