# Generated by Django 4.0.6 on 2022-09-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commendations', '0006_alter_milestone_milestone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='awarded',
            field=models.BooleanField(default=False, verbose_name='Awarded'),
        ),
    ]
