# Generated by Django 4.2.1 on 2023-07-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commendations", "0007_milestone_awarded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="milestone_type",
            field=models.IntegerField(
                choices=[
                    (25, "Dean's Certificate for 25 commendations"),
                    (50, "Green Jr School spirit badge for 50 commendations"),
                    (100, "Blue Jr School spirit badge for 100 commendations"),
                    (150, "Gold Jr School spirit badge for 150 commendations"),
                ],
                verbose_name="Milestone Type",
            ),
        ),
    ]
