# Generated by Django 4.2.1 on 2023-09-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commendations", "0008_alter_milestone_milestone_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="commendation",
            name="inside_outside",
            field=models.CharField(
                choices=[("I", "Inside Classroom"), ("O", "Outside Classroom")],
                default="I",
                max_length=1,
                verbose_name="Commendation Location",
            ),
        ),
    ]
