# Generated by Django 4.2.1 on 2023-10-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commendations", "0009_commendation_inside_outside"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commendation",
            name="inside_outside",
            field=models.CharField(
                choices=[
                    ("I", "In class"),
                    ("O", "Out of class"),
                    ("E", "Extracurricular"),
                ],
                default="I",
                max_length=1,
                verbose_name="Commendation Location",
            ),
        ),
    ]
