# Generated by Django 4.2 on 2023-05-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0004_teacher_is_management"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="house_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Anderson"),
                    ("B", "Begg"),
                    ("R", "Ross"),
                    ("H", "Herron"),
                    ("S", "Somerville"),
                ],
                default="",
                max_length=20,
                verbose_name="House Group",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="staff_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=2,
                unique=True,
                verbose_name="Staff Code",
            ),
        ),
    ]
