# Generated by Django 4.0.6 on 2022-09-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.TextField(choices=[('Done', 'Done'), ('Replied', 'Replied'), ('Not Replied', 'Not Replied')], default='Not Replied', max_length=20),
        ),
    ]
