name: Pull request testing

on:
  pull_request:
  push: 
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ALLOWED_HOSTS: '*'
        DEBUG: True
        KAMAR_AUTH_PASSWORD: 'kamar'
        KAMAR_AUTH_USERNAME: 'Password1234'
      run: |
        coverage run manage.py test --noinput

    - name: Upload as artifact
      uses: actions/upload-artifact@v3
      with:
        name: .coverage
        path: .coverage

    - name: Generate coverage tests
      run: |
        coverage report -m
        coverage xml

    - name: Report coverage to DeepSource
      uses: deepsourcelabs/test-coverage-action@v1.0.0
      with:
        key: python
        dsn: ${{ secrets.DEEPSOURCE_DSN }}

    - name: Check formatting with black
      run: |
        black --check .
