name: Pull request testing

on:
  pull_request:

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ALLOWED_HOSTS: '*'
        DEBUG: True
        KAMAR_AUTH_PASSWORD: 'kamar'
        KAMAR_AUTH_USERNAME: 'Password1234'
      run: |
        python manage.py test --failfast --noinput --verbosity=3 --parallel

    - name: Check formatting with black
      run: |
        black --check .

    - name: Generate coverage report
      run: |
        coverage report -m
        coverage xml -o coverage.xml

      - name: Report results to DeepSource
        run: |
          coverage xml

        # Install deepsource CLI
          curl https://deepsource.io/cli | sh

        # From the root directory, run the report coverage command
          ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml

        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}